services:
  db:
    container_name: notification_service_db
    image: postgres:latest
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"